 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/set_lists", type: :request do
  # SetList. As you add validations to SetList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SetList.create! valid_attributes
      get set_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      set_list = SetList.create! valid_attributes
      get set_list_url(set_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_set_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      set_list = SetList.create! valid_attributes
      get edit_set_list_url(set_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SetList" do
        expect {
          post set_lists_url, params: { set_list: valid_attributes }
        }.to change(SetList, :count).by(1)
      end

      it "redirects to the created set_list" do
        post set_lists_url, params: { set_list: valid_attributes }
        expect(response).to redirect_to(set_list_url(SetList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SetList" do
        expect {
          post set_lists_url, params: { set_list: invalid_attributes }
        }.to change(SetList, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post set_lists_url, params: { set_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested set_list" do
        set_list = SetList.create! valid_attributes
        patch set_list_url(set_list), params: { set_list: new_attributes }
        set_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the set_list" do
        set_list = SetList.create! valid_attributes
        patch set_list_url(set_list), params: { set_list: new_attributes }
        set_list.reload
        expect(response).to redirect_to(set_list_url(set_list))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        set_list = SetList.create! valid_attributes
        patch set_list_url(set_list), params: { set_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested set_list" do
      set_list = SetList.create! valid_attributes
      expect {
        delete set_list_url(set_list)
      }.to change(SetList, :count).by(-1)
    end

    it "redirects to the set_lists list" do
      set_list = SetList.create! valid_attributes
      delete set_list_url(set_list)
      expect(response).to redirect_to(set_lists_url)
    end
  end
end
